	; Strings to accompany h2.zap

	.GSTR STR?97,""
	.GSTR STR?916,"   "
	.GSTR STR?917,"     "
	.GSTR STR?918,"        "
	.GSTR STR?919,"           "
	.GSTR STR?98,"        Failed."
	.GSTR STR?758,"      5   Picking the clover"
	.GSTR STR?195,"     ****  You have died  ****"
	.GSTR STR?237,"     ****  You have failed in life  ****"
	.GSTR STR?279,"     ****  You were the wrong person at the wrong time  ****"
	.GSTR STR?760,"     10   Enter the Dark from Magrathea"
	.GSTR STR?770,"     10   Get the Green Cube (frob of randomness)"
	.GSTR STR?763,"     15   Escape the mice"
	.GSTR STR?759,"     15   Getting Marvin to follow you"
	.GSTR STR?761,"     15   Leave the Dark (to Below Magrathea)"
	.GSTR STR?774,"     15   Pour a spoonful of Pan Galactic Gargle Blaster into the meal"
	.GSTR STR?764,"     15   Sneak into the 1st Class"
	.GSTR STR?767,"     15   Write the right name on the phone"
	.GSTR STR?765,"     20   Get the first-class access card"
	.GSTR STR?769,"     20   Get the Red Rhombicosidodecahedron"
	.GSTR STR?762,"     20   Leave the 'Interview'"
	.GSTR STR?773,"     25   Escape your building as Dirk"
	.GSTR STR?779,"     25   Escaping the Stunt Ship"
	.GSTR STR?776,"     25   Finishing making the meal"
	.GSTR STR?775,"     25   Getting Clyde to open the safe"
	.GSTR STR?771,"     25   Leave the Golgafrincham Ark B"
	.GSTR STR?772,"     25   Return from the Big Bang Burger Bar"
	.GSTR STR?768,"     25   Speak the Philosophical Word"
	.GSTR STR?766,"     25   Stun the Morpher Captain"
	.GSTR STR?780,"    400   TOTAL POINTS"
	.GSTR STR?212,"    Reginald Markenplatt
    Founder of Magrathea Corps.
    86 standard yrs."
	.GSTR STR?716,"  - Finally, the Pan Galactic Gargle Blaster, also in the Kitchen (again, see another section - How Do I Safely Add the PGGB to the Meal?)"
	.GSTR STR?714,"  - The peanuts in the Planetary Design Workshop"
	.GSTR STR?715,"  - The water in the Kitchen (see How Do I Get Water?)"
	.GSTR STR?713,"  - You can find the meat on the Golgafrincham Ark B"
	.GSTR STR?851,"  1   Pick the plant on the Ledge"
	.GSTR STR?852,"  2   Upon being sent to the Dark from Below Magrathea"
	.GSTR STR?853,"  3   Play with the chatterbox until you get the number 12345"
	.GSTR STR?854,"  4   Examine the snow lizard meat after asing the Ark B captain about it"
	.GSTR STR?855,"  5   Looking at Footnote 3"
	.GSTR STR?856,"  6   Type FOOTNOTE without any number"
	.GSTR STR?857,"  7   Examine the portal in the Car Park"
	.GSTR STR?858,"  8   After eating the dinner with Pan Galactic Gargle Blaster in it"
	.GSTR STR?859,"  9   Looking at Footnote 5"
	.GSTR STR?757,"  SCORE   ACTION"
	.GSTR STR?329," 

   A frob is classified as a small object which can be changed or manipulated in form. The form you will generally find a frob in is when it appears as just a colourful object. However, if you are lucky you may find one in its true form, or be able to change it to that. The true form relates to a certain statistic, such as wealth, knowledge, or charm. It is said that all the frobs were made from the splintered remains of the 5 pieces of the Wikkit Key. Some true forms include a knife, a perfect sphere, a complex shape, or a wiggly line in multiple dimensions (whilst visible in 3D without needing an alternate entity, if that makes sense, which it doesn't). 
   Now, this may seem Like the premise of an epic hero film or something, but frobs are known all across the galaxy as things which you might use every day. Try looking for one! You can probably find a frob in in the bathroom, or maybe in the garden.

Possible uses of the word FROB:
    - Old man, give me the frob
    - ""She took the frob and threw it in the test tube."""
	.GSTR STR?0," (something).]
"
	.GSTR STR?712," **** EXTREME SPOLIERS AHEAD ****"
	.GSTR STR?860," 10   Cheating at the game by saying the Philosophical word in the Fjords without being able to know it during this lifetime (in fact, cheating TWICE in a way)"
	.GSTR STR?861," 11   This footnote is not referenced"
	.GSTR STR?862," 12   Also not referenced"
	.GSTR STR?863," 13   ASK GUIDE ABOUT 42"
	.GSTR STR?864," 14   Reading the last words book in the PDW a few times"
	.GSTR STR?865," 15   ASK [something] ABOUT DIRK after you escape Dirk's building"
	.GSTR STR?777," 499975   Eating the meal (with a spoonful of PGGB in it)"
	.GSTR STR?915," bored"
	.GSTR STR?12," brain the size of a planet"
	.GSTR STR?6," But then again you must already know that, since you bought one."
	.GSTR STR?1034," freezing"
	.GSTR STR?328," FROB (plural FROBS)"
	.GSTR STR?995," grapefruit"
	.GSTR STR?914," impatient"
	.GSTR STR?23," is a green cube. ""Ah! A green frob of randomness!"" Slarty declares. ""And already its true form! If miracles were not just high levels of improbability, they would be otherwise, and that would be less fun, so... Um."" He smiles halfheartedly at his odd logic, and looks away in a bout of confusion.
"
	.GSTR STR?282," is electric therefore it breaks, electrocuting the captain. A man with the number 2 printed on his jacket comes rushing in shouting ""What were those screams?"", before noticing the dead man in the bathtub. Correctly assuming that you were responsible for his 'murder', Number Two brings out his gun and ends your life. What a way to go."
	.GSTR STR?488," isn't in the vocabulary that you can use with me"
	.GSTR STR?10," matter transference beam"
	.GSTR STR?482," means, but I don't"
	.GSTR STR?484," means. But for now, I don't"
	.GSTR STR?490," means. No, actually, don't"
	.GSTR STR?313," N = Next"
	.GSTR STR?216," Of course, you had to walk over to the door, and then push the button, all in one. So you had no chance."
	.GSTR STR?913," out a loud yawn"
	.GSTR STR?994," pear"
	.GSTR STR?41," President of the Galaxy"
	.GSTR STR?308," RETURN = See hint"
	.GSTR STR?315," RETURN = See topics"
	.GSTR STR?499," stay at your side"
	.GSTR STR?327," that bad, because soon you find yourself on the floor, with an extreme case of liver failure.
Perhaps you should have gotten a subscription to that club a few miles from home, a few months before it was destroyed.
But oh well. You didn't."
	.GSTR STR?30," the legendary lost planet of Magrathea"
	.GSTR STR?486," to complete the game"
	.GSTR STR?498," trail along"
	.GSTR STR?1033," vast"
	.GSTR STR?1036," very big"
	.GSTR STR?497," walk a few steps behind"
	.GSTR STR?500," walk along with you"
	.GSTR STR?162," would appreciate that."
	.GSTR STR?21," you've been trying to get rid of it for years."
	.GSTR STR?290,"
[DEBUG: HELLO called]
"
	.GSTR STR?146,"
[DEBUG: I opened the thing! Report this if you think it's a bug!]
"
	.GSTR STR?152,"
[DEBUG: It is closed, that's why. Or at least it should be.]
"
	.GSTR STR?240,"
[DEBUG: It should be fixed!]
"
	.GSTR STR?287,"
[DEBUG: MRKUG called]
"
	.GSTR STR?289,"
[DEBUG: NO called]
"
	.GSTR STR?185,"
[DEBUG: performing V-SAY]
"
	.GSTR STR?293,"
[DEBUG: PRSI visible so running statement]
"
	.GSTR STR?291,"
[DEBUG: running V-SAY through speech objects]
"
	.GSTR STR?174,"
[DEBUG: running V-SAY]
"
	.GSTR STR?292,"
[DEBUG: running V-TELL through qcontext]
"
	.GSTR STR?184,"
[DEBUG: running V-TELL]
"
	.GSTR STR?179,"
[DEBUG: V-SAY, acting out V-HELLO]
"
	.GSTR STR?178,"
[DEBUG: V-SAY, acting out V-MRKUG]
"
	.GSTR STR?176,"
[DEBUG: V-SAY, acting out V-NO]
"
	.GSTR STR?177,"
[DEBUG: V-SAY, acting out V-YES]
"
	.GSTR STR?175,"
[DEBUG: V-SAY, qcontext to V-TELL]
"
	.GSTR STR?186,"
[DEBUG: V-TELL, dobj=player]
"
	.GSTR STR?187,"
[DEBUG: V-TELL, talking to person]
"
	.GSTR STR?288,"
[DEBUG: YES called]
"
	.GSTR STR?4,"
[That's all.]
"
	.GSTR STR?249,"
In actual fact, that ride took away quantitudes of protein from your system, which led to a violent allergic reaction, and your sudden death. Your friends, being useless, never do find a way out of the stunt ship so they ungracefully embrace death by radiation poisoning and a much quicker zero-point-one degree burn, and they also die.

The only one who survives in this situation appears to be Marvin. He uses a matter tranference beam onboard the ship to escape, yet not all goes well for him either, because he spends the rest of time on the marsh planet Squornshellous Zeta, whose only inhabitants are a race of mattresses, all of whom are called Zem and are very happy. This is awufully bad luck for Marvin, but who really cares about Marvin?
Look, what I'm really trying to get across to you is the fact that you have died, and that's final. Just once more for a luckier run next time:"
	.GSTR STR?157,"
RUNNING POUR 1
"
	.GSTR STR?158,"
RUNNING POUR 2
"
	.GSTR STR?159,"
RUNNING POUR FAIL
"
	.GSTR STR?160,"
RUNNING POUR FLOP
"
	.GSTR STR?147,"
TEST 4
"
	.GSTR STR?209,"
The mice, who have spent the last few minutes loading their guns while you were doing whatever you had been doing, now send you to the darkness. Wait, no, that's just you."
	.GSTR STR?234,"""Accepted."""
	.GSTR STR?580,"""Here I am, brain the size of a planet..."""
	.GSTR STR?8,"""Oh...you're trying to figure that out also? The manual's not much help, is it? By the way, do you know your score? I don't. My computer doesn't have a status line."""
	.GSTR STR?57,"""Well, you are the only human alive that was living on Earth when it was destroyed. So, the Question to the Answer of life, the Universe and Everything should be somewhere in your brain, just waiting to be found."
	.GSTR STR?13,"""Why? Why not?"""
	.GSTR STR?422,"#unrecord"
	.GSTR STR?420,"$refresh"
	.GSTR STR?433,"$scoreshot"
	.GSTR STR?421,"$verify"
	.GSTR STR?432,"$weight"
	.GSTR STR?781,"(Note: You get minus thirty points for asking Marvin about the point of life, or destroying your meal in the oven.)"
	.GSTR STR?677,"(So you don't waste objects, you can always place the rum glass in to get the wine glass.)"
	.GSTR STR?411,"(somethin"
	.GSTR STR?613,"(SPOILERS AHEAD)"
	.GSTR STR?193,"****  You have failed in life  ****"
	.GSTR STR?257,"."
	.GSTR STR?7,". Also see the entries on "
	.GSTR STR?272,". There was a way to the northwest, but, well... The pillar has collapsed, so the northwest trail is over a hundred metres up on the glacier. Oh. And I forgot to mention - when you hit the water, you did die of shock."
	.GSTR STR?40,".
"
	.GSTR STR?275,".

What a wasted opportunity."
	.GSTR STR?43,".""
"
	.GSTR STR?18,"..."
	.GSTR STR?883,"...And other commands. (Once you are done with typing out your command, press ENTER to get the response.)
To return to the previous menu, press Q, or to return to playing the game, press the escape key."
	.GSTR STR?880,"...ASK [person] ABOUT/FOR [object/subject]..."
	.GSTR STR?874,"...I - for your INVENTORY..."
	.GSTR STR?875,"...L - to LOOK AROUND..."
	.GSTR STR?879,"...PULL [object]..."
	.GSTR STR?878,"...SEARCH [object]..."
	.GSTR STR?881,"...SMELL, FEEL, TASTE, LISTEN..."
	.GSTR STR?877,"...TAKE/DROP [object]..."
	.GSTR STR?561,"...who knows why? And they've left you here, haven't they?"
	.GSTR STR?876,"...X [object] - EXAMINE [object]..."
	.GSTR STR?882,"...YES/NO (in response to a question by the computer, or a person)..."
	.GSTR STR?106,"/ / \ \"
	.GSTR STR?74,": "
	.GSTR STR?80,":
"
	.GSTR STR?31,"? Well, sorry, but it looks like that whole 'understanding' thing was all fake. Not that I am actually sorry I don't think I'm ever trusting humans again.."
	.GSTR STR?105,"["
	.GSTR STR?705,"[...]"
	.GSTR STR?960,"[..And I have a crazy person controlling me. Hmmgrbllgh....]"
	.GSTR STR?107,"[_/"
	.GSTR STR?102,"[`\   /`]"
	.GSTR STR?646,"[This space intentionally left blank]"
	.GSTR STR?58,"[You didn't say w"
	.GSTR STR?103,"\ \ / /"
	.GSTR STR?108,"\_] "
	.GSTR STR?104,"]"
	.GSTR STR?250,"]
"
	.GSTR STR?258,"14,867"
	.GSTR STR?259,"19,900"
	.GSTR STR?778,"-499950   Gradually after eating the meal and becoming depressed"
	.GSTR STR?61,"A brave, Zen-like effort. It fails."
	.GSTR STR?1021,"a cluttered dorm"
	.GSTR STR?398,"A computer rests against the wall."
	.GSTR STR?400,"A galactic security agent stands here, swiping through lists of top-secret agency stuff on his phone."
	.GSTR STR?394,"A large, pink bath which contains frothy water sits in the centre of the room. 
Inside the bath sits a man with a captain's hat on."
	.GSTR STR?401,"A normal phone, not too unordinary or high-tech (except touchscreen and stuff), is in the security agent's hands."
	.GSTR STR?941,"a polar bear rises up behind you and lands right on top of you"
	.GSTR STR?403,"A service robot, is lying around, acting very relaxed."
	.GSTR STR?997,"A single drop comes out of the tap"
	.GSTR STR?339,"A small plant is poking out of the ground, through the dislodged soil."
	.GSTR STR?999,"A steady stream of water comes out of the tap, but the water is so hot that it eveaporates almost immediately"
	.GSTR STR?928,"A stong gust knocks you over; you get back up again."
	.GSTR STR?503,"A sudden blackout around you sends you reeling, pulling you forwards into a pit of darkness so alarmingly empty it could have been death..."
	.GSTR STR?386,"A telephone stands a survivor of the tidal wave of papers."
	.GSTR STR?389,"A tidal wave of papers scatters the table."
	.GSTR STR?964,"A totally unhelpful idea."
	.GSTR STR?230,"Accepted."
	.GSTR STR?969,"accomplishes nothing"
	.GSTR STR?325,"actual"
	.GSTR STR?1060,"actually"
	.GSTR STR?872,"ADDITIONAL COMMANDS"
	.GSTR STR?813,"ADVICE"
	.GSTR STR?172,"After a long and totally random argument with itself, the God decides that it cannot be bothered to rule such a Universe if people like you are living in it (not that it was really ruling the Universe; this God didn't even create it - this was just a higher tier god). Its cultists drive it to destroy itself, bringing down the part of the galaxy that you are in along with it. This kills 789 billion people, including you."
	.GSTR STR?650,"After some time, you may notice that he continually walks on one route, back and forth."
	.GSTR STR?654,"After the idiot goes through the second class access door, you can walk in."
	.GSTR STR?54,"After waiting for a few minutes, you place the phone back down again.
"
	.GSTR STR?664,"After you've done that, you need to think (obviously). What can you use?"
	.GSTR STR?194,"again"
	.GSTR STR?344,"Alarms, signals, sirens, shouting, banging, flashing lights, whirring computers, pounding feet, all around. You can hear someone saying something, presumably to you, but like any song where you can't tell if it is being sung in English or a foreign language (which shouldn't mean much now; you have a babel fish), you can't tell what is being said.

The computer is hot against your back, and the bullets ricochet off the walls, barely missing you. Can you escape?"
	.GSTR STR?319,"alcohol"
	.GSTR STR?814,"ALCOHOL"
	.GSTR STR?735,"Alright, how do I catch this captain?"
	.GSTR STR?559,"Alright. Secondly, about your friends."
	.GSTR STR?547,"Also, where did you get this gun idea from in the first place?"
	.GSTR STR?192,"Although that is in about 25 minutes, so I'll skip quickly to that part, and immediately past it. Anyway, what was I saying? Oh yes."
	.GSTR STR?393,"Although you're on the bridge, you don't seem to be able to leave."
	.GSTR STR?939,"an enormous pillar rises out of the ground, and you were on it. Unfortunately for you, it was so unstable that you slipped off it and fell over fifty meters to your death on the ice"
	.GSTR STR?166,"an opening in"
	.GSTR STR?173,"and all the molecules in your body are wrenched apart. When it comes the part where the molcules are meant to be moved to another location, they fail to find a transference beam, reluctantly return to the same shape they were in before but fail to find that as well, as they had drifted too far apart; and the story ends without any memory of death. But still..."
	.GSTR STR?604,"And don't be so sensitive about my jokes."
	.GSTR STR?620,"And finally (with feeling), if there is a warm lump under your fingers, you are going to the ship of the Morphers (you'll understand if you haven't already); and if the lump is cold you will arrive at the Fjords of Norway."
	.GSTR STR?668,"And make you wise if you survive."
	.GSTR STR?496,"And so's your old man!"
	.GSTR STR?585,"And the fact that it is playing happy music."
	.GSTR STR?682,"And what about the head cook?"
	.GSTR STR?870,"And, NE(northeast), NW(northwest), SE(southeast), and SW(southwest)."
	.GSTR STR?122,"angry"
	.GSTR STR?425,"annihalate"
	.GSTR STR?805,"ANNIHALATE something?"
	.GSTR STR?220,"another"
	.GSTR STR?202,"anything that powerful"
	.GSTR STR?583,"Apparently not."
	.GSTR STR?434,"aquamarine"
	.GSTR STR?1005,"arrKkYYUUi"
	.GSTR STR?222,"Arthur Dent"
	.GSTR STR?946,"Arthur Philip Deodat, Testy X7G663, Dimwit Flathead"
	.GSTR STR?269,"as"
	.GSTR STR?869,"As well as UP, DOWN, IN & OUT."
	.GSTR STR?634,"As you can tell, that doesn't work. Too much action in one turn. Try splitting it up into shorter moves."
	.GSTR STR?49,"As you leap off the edge, a spark of an idea lights in your head. During the few seconds in which you hang in midair, the idea reveals itself as common sense and berates you for doing such a stupid thing as actually jumping off the edge of over one hundred-metre cliff walls. Alas, this message doesn't make much of a difference to your mental state, because several milliseconds later, while you process this information, you hit "
	.GSTR STR?78,"ask about"
	.GSTR STR?625,"ASK BENJY ABOUT THE POINT OF THE GAME. Or Percy."
	.GSTR STR?624,"Ask them."
	.GSTR STR?899,"ASK ZAPHOD BEEBLEBROX FOR A PAN GALACTIC GARGLE BLASTER."
	.GSTR STR?786,"asking Marvin about life, and then again? (you may want to save first...)"
	.GSTR STR?524,"asleep"
	.GSTR STR?663,"At this point, you should probably look at the section entitled IS THE KITCHEN USEFUL?"
	.GSTR STR?627,"At this point, you will need to distract the mice to get through. When the mice tell you to eat fruit, try eating the fruit, or saying YES/OK."
	.GSTR STR?125,"attack"
	.GSTR STR?799,"attempting to swim in the water on the tray?"
	.GSTR STR?439,"auto-sign"
	.GSTR STR?815,"BABEL FISH"
	.GSTR STR?378,"Back down into the water? No thanks."
	.GSTR STR?444,"backstreet"
	.GSTR STR?1023,"balancing yourself on a piece of rock jutting out"
	.GSTR STR?280,"BAM!!

"
	.GSTR STR?135,"bang"
	.GSTR STR?549,"Be specific."
	.GSTR STR?441,"beeblebrox"
	.GSTR STR?643,"BELOW MAGRATHEA"
	.GSTR STR?991,"Benjy"
	.GSTR STR?1030,"big"
	.GSTR STR?816,"BIG BANG BURGER BAR"
	.GSTR STR?204,"black metallic box"
	.GSTR STR?198,"blue frob"
	.GSTR STR?201,"blue frob of power"
	.GSTR STR?452,"blue-rimm"
	.GSTR STR?1057,"Brian Rushton"
	.GSTR STR?373,"brick"
	.GSTR STR?95,"Brief"
	.GSTR STR?265,"broken brick"
	.GSTR STR?532,"brushing her hair"
	.GSTR STR?436,"bugblatter"
	.GSTR STR?450,"bug-fixin"
	.GSTR STR?562,"But yes, they returned to the ship. Didn't you read?"
	.GSTR STR?669,"But you can't drink it. (Your brain tells you not to.)"
	.GSTR STR?685,"But you should be more specific than that."
	.GSTR STR?692,"But..."
	.GSTR STR?223,"car park access door"
	.GSTR STR?224,"car park access panel"
	.GSTR STR?789,"CHANGE CHANNEL with the radio? And then again? (this could actually save your life...)"
	.GSTR STR?132,"channel bed"
	.GSTR STR?787,"checking your rank when you type SCORE (including when you have negative points)?"
	.GSTR STR?350,"Choice: you can go inwards to the north (where there is a time-teleport cubicle) or to the east (to Hotblack Desiato's ship, among others)."
	.GSTR STR?467,"clattering"
	.GSTR STR?127,"close"
	.GSTR STR?111,"closed"
	.GSTR STR?301,"Clyde"
	.GSTR STR?302,"Clyde, the service robot, is lying around, acting very relaxed."
	.GSTR STR?303,"Clyde, the service robot, is lying around, acting very relaxed. On the back of his head is a strange panel."
	.GSTR STR?410,"cocksucker"
	.GSTR STR?1010,"cold"
	.GSTR STR?989,"Cold showers."
	.GSTR STR?962,"Complete waste of time."
	.GSTR STR?492,"Computers aren't impressed by naughty words!"
	.GSTR STR?267,"console"
	.GSTR STR?153,"contain"
	.GSTR STR?471,"contraption"
	.GSTR STR?800,"COUNT THE KEYS (the keyset...)"
	.GSTR STR?817,"CRICKET"
	.GSTR STR?253,"cupboard"
	.GSTR STR?512,"dancing"
	.GSTR STR?936,"Dare sonley wunpa cent tchanssov dare thyu no."" (Footnote 14)"
	.GSTR STR?221,"Dark"
	.GSTR STR?622,"DARK"
	.GSTR STR?360,"Darkness"
	.GSTR STR?527,"deep in thought"
	.GSTR STR?982,"Degenerate"
	.GSTR STR?462,"desiato's"
	.GSTR STR?796,"destroying the painting?"
	.GSTR STR?296,"did"
	.GSTR STR?534,"Did I miss anything from the first game?"
	.GSTR STR?535,"Did you play it?"
	.GSTR STR?569,"Did you really think tasting it or smelling it will work?"
	.GSTR STR?674,"Did you use the rum glass?"
	.GSTR STR?238,"ding"
	.GSTR STR?219,"Dirk Gently"
	.GSTR STR?322,"Disaster Area"
	.GSTR STR?818,"DISASTER AREA"
	.GSTR STR?428,"disconnect"
	.GSTR STR?241,"dish of meat"
	.GSTR STR?298,"dish of vegan snow lizard meat"
	.GSTR STR?92,"do"
	.GSTR STR?1000,"Do you copy?"
	.GSTR STR?550,"Do you mean the blue frob or the Thing?"
	.GSTR STR?540,"Do you really think that's a good idea?"
	.GSTR STR?595,"Does this make sense to you?"
	.GSTR STR?579,"Does this next quote make any sense to you?"
	.GSTR STR?968,"doesn't do anything"
	.GSTR STR?268,"Doing that with"
	.GSTR STR?792,"doing things to the bottles the mice are in?"
	.GSTR STR?294,"Done."
	.GSTR STR?806,"DON'T do something?"
	.GSTR STR?744,"Don't forget to keep moving around to avoid the sandcrab."
	.GSTR STR?901,"DONT WAIT."
	.GSTR STR?63,"down"
	.GSTR STR?415,"downstairs"
	.GSTR STR?797,"drinking the Santrigiean Mineral Water?"
	.GSTR STR?109,"drive"
	.GSTR STR?276,"dropping"
	.GSTR STR?726,"During the game so far, have you noticed a utensil for that sort of thing?"
	.GSTR STR?609,"Each of the senses lead to different areas of the game."
	.GSTR STR?1009,"Ea-ea"
	.GSTR STR?819,"EARTH"
	.GSTR STR?66,"east"
	.GSTR STR?793,"eating fruit?"
	.GSTR STR?520,"eating with relish"
	.GSTR STR?615,"Either way, to leave the Dark from here, you need to TALK TO BLUR."
	.GSTR STR?723,"Else, well... I'm sorry about that."
	.GSTR STR?88,"empti"
	.GSTR STR?996,"end"
	.GSTR STR?412,"end.of.input"
	.GSTR STR?1032,"endless"
	.GSTR STR?1014,"evaporate"
	.GSTR STR?414,"everything"
	.GSTR STR?795,"examining the painting?"
	.GSTR STR?884,"EXAMPLE COMMANDS"
	.GSTR STR?610,"Except taste."
	.GSTR STR?907,"extraordinary"
	.GSTR STR?984,"Failure"
	.GSTR STR?254,"fall"
	.GSTR STR?252,"FAMOUS LAST WORDS:"
	.GSTR STR?1024,"feeling the cold"
	.GSTR STR?507,"fiddles with a random mechanism for a while, then turns his attention to something else"
	.GSTR STR?75,"FIND"
	.GSTR STR?708,"Find some dinner."
	.GSTR STR?593,"First, read the footnote."
	.GSTR STR?440,"first-cla"
	.GSTR STR?556,"Firstly, about the Guide."
	.GSTR STR?266,"fizzle"
	.GSTR STR?89,"fli"
	.GSTR STR?1019,"flicker"
	.GSTR STR?464,"flickering"
	.GSTR STR?324,"floor"
	.GSTR STR?1049,"flopp"
	.GSTR STR?850,"FN#   HOW TO GET IT"
	.GSTR STR?531,"following you"
	.GSTR STR?920,"follows you"
	.GSTR STR?1051,"footl"
	.GSTR STR?848,"FOOTNOTES"
	.GSTR STR?782,"FOR YOUR AMUSEMENT"
	.GSTR STR?558,"For your information, it's probably still on the ship."
	.GSTR STR?820,"FORD PREFECT"
	.GSTR STR?300,"fork"
	.GSTR STR?474,"forty-two"
	.GSTR STR?821,"FORTY-TWO"
	.GSTR STR?473,"four-leaf"
	.GSTR STR?1028,"freezing"
	.GSTR STR?200,"frob"
	.GSTR STR?822,"FROBS"
	.GSTR STR?591,"From the Blighted Ground, go SE. SW. DOWN. PICK PLANT."
	.GSTR STR?504,"From the sea-torn grounds of the Bermuda Triangle on Earth to the pits of Hell somewhere in your imagination, the dark is about as satisfying as having a good, solid kick in the head.

Although the after effects of darkness make you wish you had chosen the kick..."
	.GSTR STR?330,"Froody."
	.GSTR STR?435,"frustration"
	.GSTR STR?5,"Galactic Security Agency"
	.GSTR STR?823,"GALACTIC SECURITY AGENCY"
	.GSTR STR?904,"GENERAL COMMANDS"
	.GSTR STR?22,"Genuine People Personalities"
	.GSTR STR?126,"get in"
	.GSTR STR?359,"Get on the stage? Sorry, I'm not going to let you do it."
	.GSTR STR?687,"Getting the first-class access card"
	.GSTR STR?1008,"Ggght"
	.GSTR STR?976,"Give me some more specifics, and I'll help."
	.GSTR STR?790,"giving the radio to Marvin once you're down in the Whale Crater, and looking around?"
	.GSTR STR?511,"glances at the computer to see if anything has changed, then shakes his head and looks away"
	.GSTR STR?110,"go"
	.GSTR STR?895,"GO NORTH AND THEN EAST."
	.GSTR STR?1040,"go to the"
	.GSTR STR?885,"GO TO THE NORTH."
	.GSTR STR?886,"GO UP."
	.GSTR STR?751,"Good? Ok, You'll need to WRITE WITH PEN ON PHONE."
	.GSTR STR?510,"grabs a test tube, shakes it, and then puts it back"
	.GSTR STR?1031,"grand"
	.GSTR STR?824,"GREAT UNANSWERED QUESTION"
	.GSTR STR?130,"ground"
	.GSTR STR?825,"GUIDANCE"
	.GSTR STR?811,"GUIDE ENTRIES"
	.GSTR STR?217,"hall"
	.GSTR STR?86,"has"
	.GSTR STR?970,"has no desirable effect"
	.GSTR STR?589,"Have you even found it?"
	.GSTR STR?612,"Have you noticed how sometimes the sense response will differ?"
	.GSTR STR?672,"Have you noticed some glasses in the cupboard?"
	.GSTR STR?690,"Have you noticed the wine bottle?"
	.GSTR STR?784,"Have you tried..."
	.GSTR STR?691,"He finishes the wine - no problem - if you just give him just wine."
	.GSTR STR?1046,"he phone begins to ring"
	.GSTR STR?1045,"he phone is ringing"
	.GSTR STR?1047,"he phone is ringing, but you can't be bothered to get it"
	.GSTR STR?44,"he Restaurant at the End of the Universe"
	.GSTR STR?698,"He tells you to talk to him."
	.GSTR STR?1038,"head"
	.GSTR STR?826,"HEART OF GOLD"
	.GSTR STR?459,"heat-proo"
	.GSTR STR?739,"Help! The captain got angry when I shot it and transformed into a giant sandcrab!"
	.GSTR STR?137,"here"
	.GSTR STR?812,"Here's a complete list of things that you can CONSULT the Hitchhiker's Guide about. You should use it only as a last resort, or for your interest once you've finished the game."
	.GSTR STR?931,"He's unstoppable!"""
	.GSTR STR?494,"Hey, save that talk for the locker room!"
	.GSTR STR?438,"high-tech"
	.GSTR STR?893,"HIT THE ALIEN WITH THE DOG BONE."
	.GSTR STR?827,"HITCHHIKER'S GUIDE"
	.GSTR STR?785,"hitting/kissing Marvin?"
	.GSTR STR?112,"holding it"
	.GSTR STR?644,"Hooray! I'm finally at the Restaurant at the End of the Universe. Now what?"
	.GSTR STR?570,"Hopefully not."
	.GSTR STR?828,"HOTBLACK DESIATO"
	.GSTR STR?755,"HOW ALL THE POINTS ARE SCORED"
	.GSTR STR?717,"How do I get water?"
	.GSTR STR?724,"How do I safely add the Pan Galactic Gargle Blaster to the meal?"
	.GSTR STR?626,"How do I stop being killed?"
	.GSTR STR?542,"How does the Kill-O-Zap gun work?"
	.GSTR STR?557,"How should that be anyone else's problem but your own?"
	.GSTR STR?975,"How?"
	.GSTR STR?445,"human-mad"
	.GSTR STR?27,"Humans are so depressingly "
	.GSTR STR?151,"hurt"
	.GSTR STR?28,"I assume you mean: "
	.GSTR STR?930,"I can fly!"""
	.GSTR STR?932,"I can handle this gun."""
	.GSTR STR?480,"I don't know the word"
	.GSTR STR?483,"I guess I'll have to learn what"
	.GSTR STR?623,"I just came out of the dark! What am I doing with these mice?"
	.GSTR STR?732,"I keep getting killed by objects in the room that aren't even there!"
	.GSTR STR?1003,"I repeat,"
	.GSTR STR?1001,"I repeat:"
	.GSTR STR?986,"Idiot"
	.GSTR STR?738,"If an object appears or changes, shoot it."
	.GSTR STR?747,"If only there was actually a crab. I don't even know the word ""crab""."
	.GSTR STR?596,"If so, LEAVE NOW."
	.GSTR STR?675,"If so, you'll realise that that's not proper waiter-behaviour."
	.GSTR STR?536,"If you didn't, go back and play it. There's no point living a life you haven't started."
	.GSTR STR?721,"If you have been to the Planetary Design Workshop, then you should know if you have to restore or not."
	.GSTR STR?408,"If you have reached here, you have found a BUG! Please report it to maxfouquetogarra@gmail.com . Thanks!

... Oh - and you'll have to restore or restart to leave this damned place, or just QUIT."
	.GSTR STR?48,"If you hyperventilate and then empty your lungs, you will last about thirty seconds in the vacuum of space. However, because space is so vastly hugely mind-bogglingly big, getting picked up by another ship within those thirty seconds is almost infinitely improbable."
	.GSTR STR?551,"If you mean the Thing (in the gown), go back and replay the first game properly."
	.GSTR STR?722,"If you picked up the wrench when you were there, you can turn the bolt with that."
	.GSTR STR?693,"If you pour the two in the same glass, the idiot will think it's wine (Blaster is clear), and he will drink it."
	.GSTR STR?688,"If you started off from the first-class idiot (continued), then you should be fine. Otherwise, try reading that first."
	.GSTR STR?660,"If you try taking it, you're put off by his thretening looks."
	.GSTR STR?653,"If you were thinking about the Car Park, you can try sneaking in after the idiot walks through. It won't work."
	.GSTR STR?614,"If your sight returns to you, the description of the blur is different. If you see a small black blur, you're going to Below Magrathea. Whereas if you see a large green blur, you are returning to Milliways."
	.GSTR STR?649,"If you're asking what to do about him, you might want to look around."
	.GSTR STR?681,"If you've looked at the cupboard in the Kitchen, you should be able to tell that there are many objects you can get. But if you try to take any of them, it won't let you."
	.GSTR STR?658,"If you've read the descriptions of the first-class idiot when he passes through any of the doors, you'll notice that he has a first-class access card. And when you try entering the Car Park, you need a high-level card."
	.GSTR STR?307,"ignore"
	.GSTR STR?528,"ignoring you"
	.GSTR STR?489,"I'm just a stupid computer. Please enlighten me with what"
	.GSTR STR?957,"I'm not convinced you're allowed to be playing with this computer."
	.GSTR STR?270,"I'm sorry, but the cold was too much for you, and so you could not survive."
	.GSTR STR?601,"I'm stuck in the Dark!"
	.GSTR STR?72,"in"
	.GSTR STR?164,"in it"
	.GSTR STR?368,"In the wall is a large teleportation chamber, big enough to enter."
	.GSTR STR?133,"in the water"
	.GSTR STR?633,"In this turn, you can begin escaping. Try OUT."
	.GSTR STR?978,"Incompetent"
	.GSTR STR?246,"inside the escape pod"
	.GSTR STR?295,"Instead of having to deal with the torture of listening to Marvin talk about life, you recite a few verses of poetry. By the second line of the third verse, you have caused yourself a brain haemorrhage."
	.GSTR STR?477,"intelligence"
	.GSTR STR?829,"INTELLIGENCE"
	.GSTR STR?906,"interesting"
	.GSTR STR?423,"invisiclues"
	.GSTR STR?312,"INVISICLUES"
	.GSTR STR?310,"INVISICLUES (tm)"
	.GSTR STR?85,"is"
	.GSTR STR?972,"is a waste of time"
	.GSTR STR?509,"is admiring one of the machines scattered throughout this workshop"
	.GSTR STR?505,"is looking over his notes"
	.GSTR STR?506,"is staring at the wall behind you"
	.GSTR STR?680,"Is the Kitchen useful?"
	.GSTR STR?245,"issi"
	.GSTR STR?546,"It essentially means you must think about what you want to do. For example, THINK ABOUT KILLING MARVIN."
	.GSTR STR?55,"It has been designed to do worthless commands like that for you."
	.GSTR STR?753,"It is also useful at the BBBB, so keep it in your possession."
	.GSTR STR?235,"It leads to and from the Dining Hall to Max Quordlepleen's dressing room"
	.GSTR STR?231,"It leads to and from the Dining Hall to the Third Class"
	.GSTR STR?29,"It looks like "
	.GSTR STR?227,"It looks like it could squish you in half as you walk through it"
	.GSTR STR?236,"It might lead to the dressing room, but you can't be sure"
	.GSTR STR?667,"It says that it can knock someone out."
	.GSTR STR?742,"It should like the tin of artichokes in the Galley."
	.GSTR STR?749,"It will be useful later."
	.GSTR STR?9,"It's automatic. It won't budge."
	.GSTR STR?37,"It's not plugged into anything!"
	.GSTR STR?603,"It's not so hard. Just look around."
	.GSTR STR?543,"It's remotely based."
	.GSTR STR?52,"It's too firmly stuck in the metal of his head. "
	.GSTR STR?608,"I've been here multiple times, now. How do I leave the different senses?"
	.GSTR STR?1006,"Jhahsttts"
	.GSTR STR?1056,"Jinx"
	.GSTR STR?1052,"Joey ""Jess"" Cramsey"
	.GSTR STR?830,"JOO JANTA PERIL SENSITIVE SUNGLASSES"
	.GSTR STR?894,"JUMP."
	.GSTR STR?731,"Just go to the Bathroom (south-east from the Dorm)."
	.GSTR STR?737,"Keep looking around and memorising the objects in each room."
	.GSTR STR?281,"kidding"
	.GSTR STR?696,"KILL him?"
	.GSTR STR?898,"KILL ME."
	.GSTR STR?472,"kill-o-zap"
	.GSTR STR?91,"kiss"
	.GSTR STR?1004,"Kkhrrrrss"
	.GSTR STR?260,"klump"
	.GSTR STR?139,"Knocking on"
	.GSTR STR?84,"Known bugs:

- Odd printing of a word with WHAT-DO-YOU-WANT, eg:
   (""What do you want to take?""
    > MARVIN
    ""MarvinYou can't take Marvin!"")

- Quotations not working, probably.

"
	.GSTR STR?831,"KRIKKIT"
	.GSTR STR?188,"land"
	.GSTR STR?987,"Lemon"
	.GSTR STR?909,"let"
	.GSTR STR?82,"letter"
	.GSTR STR?273,"letting go of"
	.GSTR STR?502,"Like fog rolling in off the ocean, a shroud of blackness billows toward you. Unlike fog rolling in off the ocean, the blackness hits you like a sixteen-tonne truck..."
	.GSTR STR?46,"Like I may have mentioned before, "
	.GSTR STR?525,"listening"
	.GSTR STR?522,"listening to you"
	.GSTR STR?76,"locate"
	.GSTR STR?119,"locked"
	.GSTR STR?910,"look"
	.GSTR STR?143,"look inside"
	.GSTR STR?144,"look outside"
	.GSTR STR?148,"look through"
	.GSTR STR?149,"look up"
	.GSTR STR?515,"looking at you with suspicion"
	.GSTR STR?533,"looking sleepy"
	.GSTR STR?427,"look-inside"
	.GSTR STR?508,"looks at you deeply, as if you were a person he knew a while ago"
	.GSTR STR?983,"Loser"
	.GSTR STR?326,"lot"
	.GSTR STR?454,"loudspeaker"
	.GSTR STR?523,"lounging and chatting"
	.GSTR STR?832,"MAGRATHEA"
	.GSTR STR?465,"maintenance"
	.GSTR STR?1054,"Manon"
	.GSTR STR?833,"MARVIN"
	.GSTR STR?581,"Marvin can provide light."
	.GSTR STR?896,"MARVIN, GO DOWN TO THE LEDGE. (this commands the character Marvin to go down to the ledge)"
	.GSTR STR?396,"Marvin, the Paranoid Android, is sulking."
	.GSTR STR?834,"MATTER TRANSFERENCE BEAMS"
	.GSTR STR?1053,"Max Fog"
	.GSTR STR?1013,"melt"
	.GSTR STR?453,"microphone"
	.GSTR STR?1026,"mighty"
	.GSTR STR?728,"MILLIWAYS"
	.GSTR STR?866,"MISCELLANEOUS"
	.GSTR STR?754,"MORPHER SHIP"
	.GSTR STR?150,"move"
	.GSTR STR?191,"move around within"
	.GSTR STR?922,"moves towards you"
	.GSTR STR?867,"MOVING AROUND ROOMS"
	.GSTR STR?170,"Mriug"
	.GSTR STR?171,"Mrivg"
	.GSTR STR?169,"Mrkug"
	.GSTR STR?992,"n apple"
	.GSTR STR?1037,"n endless"
	.GSTR STR?993,"n orange"
	.GSTR STR?1035,"n uninhabitable"
	.GSTR STR?887,"NE."
	.GSTR STR?1059,"necessarily"
	.GSTR STR?950,"Nice try."
	.GSTR STR?1,"No inside"
	.GSTR STR?53,"No matter how hard you try, it just won't."
	.GSTR STR?1064,"No need."
	.GSTR STR?409,"No need. You've accomplished eveything you need to there."
	.GSTR STR?2,"No surface"
	.GSTR STR?959,"No, no, a thousand times no. Go boil an egg."
	.GSTR STR?697,"No, sorry. I just love sending you off on a mission like that."
	.GSTR STR?590,"No? Alright, I'll help you."
	.GSTR STR?611,"Nobody likes taste, anyway."
	.GSTR STR?354,"no-entry door"
	.GSTR STR?636,"Nope, it's electronic. Though you will note that there's an emergency exit button by the door."
	.GSTR STR?671,"Nope, not working."
	.GSTR STR?64,"north"
	.GSTR STR?283,"north door"
	.GSTR STR?65,"northeast"
	.GSTR STR?417,"north-east"
	.GSTR STR?71,"northwest"
	.GSTR STR?416,"north-west"
	.GSTR STR?190,"not asleep"
	.GSTR STR?966,"Not helpful."
	.GSTR STR?952,"Not likely."
	.GSTR STR?3,"Nothing"
	.GSTR STR?641,"Now I'm behind the big computer. Any help?"
	.GSTR STR?752,"Now that the show has started, you can reach the Big Bang Burger Bar from the teleportation point."
	.GSTR STR?630,"Now you're being asked questions by either the mice or the computer."
	.GSTR STR?628,"Now, you can tell this doesn't work. So maybe refuse it, by saying NO."
	.GSTR STR?911,"n't appear interested"
	.GSTR STR?912,"n't care"
	.GSTR STR?424,"obliterate"
	.GSTR STR?218,"obscured door"
	.GSTR STR?578,"Of course, you didn't know that, because you died before you could realise that. So how do you get light?"
	.GSTR STR?117,"off"
	.GSTR STR?656,"Oh no! A first class idiot! (continued)"
	.GSTR STR?647,"Oh no! A first-class idiot!"
	.GSTR STR?278,"Oh, well. I was so close, wasn't I?
"
	.GSTR STR?1007,"OIJOI"
	.GSTR STR?597,"OK, you're still here. Either you're just annoying, or absolutely useless."
	.GSTR STR?538,"Okay, not exactly. But you know what I mean."
	.GSTR STR?945,"Oliver Tressenit, Itchy, Scratchy, Styevey Hryeney"
	.GSTR STR?116,"on"
	.GSTR STR?318,"on it"
	.GSTR STR?600,"ON MAGRATHEA'S SURFACE"
	.GSTR STR?134,"on the floor"
	.GSTR STR?387,"On the floor is a chatterbox - also known as a fortune teller."
	.GSTR STR?131,"on the ground"
	.GSTR STR?129,"on the ramp"
	.GSTR STR?340,"On the table is a bowl of fruit."
	.GSTR STR?571,"Once you have gotten a satifying answer, you should be able to know almost immdiately what to do."
	.GSTR STR?592,"Once you have it, what do you normally do with these kind of things?"
	.GSTR STR?606,"One of the sense should disappear after a while."
	.GSTR STR?657,"Only read this after you've entered either the Kitchen or the First-Class Area."
	.GSTR STR?1055,"Onno Brouwer"
	.GSTR STR?702,"Oops. You're not a registered guest. How could you become a registered guest?"
	.GSTR STR?118,"open"
	.GSTR STR?635,"OPEN DOOR."
	.GSTR STR?142,"opening"
	.GSTR STR?662,"Or, when he's not awake."
	.GSTR STR?552,"Otherwise, continue."
	.GSTR STR?39,"ou stop searching"
	.GSTR STR?73,"out"
	.GSTR STR?124,"out cold"
	.GSTR STR?314,"P = Previous"
	.GSTR STR?367,"packet of peanuts"
	.GSTR STR?20,"Pan Galactic Gargle Blaster"
	.GSTR STR?458,"pan-galactic"
	.GSTR STR?835,"PAN-GALACTIC GARGLE BLASTER"
	.GSTR STR?449,"passageway"
	.GSTR STR?244,"peanuts"
	.GSTR STR?121,"peeved"
	.GSTR STR?990,"Percy"
	.GSTR STR?457,"perfomance"
	.GSTR STR?242,"piece of meat"
	.GSTR STR?243,"piece of vegan snow lizard meat"
	.GSTR STR?256,"pile of pills"
	.GSTR STR?363,"pills"
	.GSTR STR?304,"PING"
	.GSTR STR?807,"Play in VERBOSE mode in some areas?"
	.GSTR STR?530,"playing the piano"
	.GSTR STR?79,"Please use commands"
	.GSTR STR?977,"Please, explain."
	.GSTR STR?1048,"plopp"
	.GSTR STR?598,"PLUG THE PLANT INTO THE RADIO."
	.GSTR STR?518,"poised to attack"
	.GSTR STR?521,"preparing dinner"
	.GSTR STR?526,"preparing to leave"
	.GSTR STR?836,"PROTIEN"
	.GSTR STR?572,"PULL APART THE BLUE FROB."
	.GSTR STR?90,"push"
	.GSTR STR?637,"PUSH BUTTON."
	.GSTR STR?161,"Pushing"
	.GSTR STR?165,"put"
	.GSTR STR?798,"putting the Guide in the oven and then turning the oven on?"
	.GSTR STR?309,"Q = Main menu"
	.GSTR STR?316,"Q = Resume story"
	.GSTR STR?311,"Q = See hint menu"
	.GSTR STR?429,"qwertyuiop"
	.GSTR STR?156,"radio"
	.GSTR STR?128,"ramp"
	.GSTR STR?11,"Ravenous Bugblatter Beast of Traal"
	.GSTR STR?837,"RAVENOUS BUGBLATTER BEAST OF TRAAL"
	.GSTR STR?183,"reach"
	.GSTR STR?1041,"reached down to scratch your leg"
	.GSTR STR?167,"read"
	.GSTR STR?808,"Read the last words book in the PDW multiple times (if you haven't misspelled a single word)?"
	.GSTR STR?965,"Real great answer."
	.GSTR STR?225,"reception access door"
	.GSTR STR?226,"reception access panel"
	.GSTR STR?478,"recognisable"
	.GSTR STR?255,"red frob"
	.GSTR STR?297,"red frob of philosophy"
	.GSTR STR?251,"red rhombicosidodecahedron"
	.GSTR STR?451,"red-tinte"
	.GSTR STR?801,"referring to Hotblack Desiato's Ship as STUNT SHIP?"
	.GSTR STR?942,"Reginald Markenplatt, John Smith, Holly Dameson, Alburto Molla"
	.GSTR STR?101,"REGISTER NAMES"
	.GSTR STR?631,"Reply with one of the answers, trying to not disagree with yourself (you may die)."
	.GSTR STR?138,"restart"
	.GSTR STR?466,"restaurant"
	.GSTR STR?199,"ridge"
	.GSTR STR?321,"rubber"
	.GSTR STR?168,"Rubbing"
	.GSTR STR?958,"Run out on the street and say that. See what happens."
	.GSTR STR?443,"salamander"
	.GSTR STR?947,"Sam Sam Sam, (some sort of name that you can't make out), Jacky Rentear, Bugsy"
	.GSTR STR?741,"Sandcrabs are from the sea, right?"
	.GSTR STR?838,"SANTRIGINEAN MINERAL WATER"
	.GSTR STR?809,"SAY MRKUG before you've finished the Fjords course?"
	.GSTR STR?892,"SEARCH THE THING FROM MY AUNT."
	.GSTR STR?529,"searching"
	.GSTR STR?228,"second class access door"
	.GSTR STR?229,"second class access panel"
	.GSTR STR?460,"second-class"
	.GSTR STR?706,"See the Morpher Ship section if you're really stuck. Yes, I am annoying."
	.GSTR STR?16,"See under "
	.GSTR STR?123,"seem"
	.GSTR STR?1058,"seem to"
	.GSTR STR?402,"service robot"
	.GSTR STR?1016,"shake"
	.GSTR STR?180,"shoot"
	.GSTR STR?900,"SHOOT THE BUTTON WITH THE KILL-O-ZAP GUN."
	.GSTR STR?539,"Should I talk to Marvin?"
	.GSTR STR?1017,"shudder"
	.GSTR STR?937,"Shut up, kid. You are five years old; you cannot do anything!"""
	.GSTR STR?563,"SIDE NOTE: If you actually bothered to play around with objects, you would have noticed that the Guide is inside your gown, which is in the Hatchway."
	.GSTR STR?513,"sipping sherry"
	.GSTR STR?47,"Sirius Cybernetics Corporation"
	.GSTR STR?404,"sky"
	.GSTR STR?839,"SLARTIBARTFAST"
	.GSTR STR?1043,"slipped on the ice"
	.GSTR STR?1022,"slipping on the melting ice"
	.GSTR STR?93,"small penknife"
	.GSTR STR?247,"Small, Empty Ship"
	.GSTR STR?181,"smell"
	.GSTR STR?306,"smile"
	.GSTR STR?447,"smiley-fa"
	.GSTR STR?659,"So how do you get the card off of the idiot?"
	.GSTR STR?701,"So SIGN YOUR NAME ON THE PHONE."
	.GSTR STR?699,"So talk to him."
	.GSTR STR?686,"So wait until there is something that you might need."
	.GSTR STR?670,"So, try giving it to the idiot."
	.GSTR STR?661,"So, you must get it when he's not looking."
	.GSTR STR?564,"So... what IS the blue frob?"
	.GSTR STR?517,"sobbing quietly"
	.GSTR STR?873,"Some helpful verbs you will need are..."
	.GSTR STR?208,"Somewhere in the Whale Crater"
	.GSTR STR?68,"south"
	.GSTR STR?284,"south door"
	.GSTR STR?888,"SOUTH."
	.GSTR STR?67,"southeast"
	.GSTR STR?419,"south-east"
	.GSTR STR?69,"southwest"
	.GSTR STR?418,"south-west"
	.GSTR STR?840,"SPACE"
	.GSTR STR?908,"special"
	.GSTR STR?99,"SPECIAL MENTIONS"
	.GSTR STR?652,"Specifically, the door to the Dining Hall - to the Second Class."
	.GSTR STR?1050,"splash"
	.GSTR STR?299,"spoon"
	.GSTR STR?841,"SPORFE"
	.GSTR STR?182,"standing up"
	.GSTR STR?262,"step"
	.GSTR STR?495,"Step outside and say that!"
	.GSTR STR?638,"Still too much. You have to be subtle!"
	.GSTR STR?810,"STOP THE SHIP while inside the Stunt Ship?"
	.GSTR STR?263,"strange gun"
	.GSTR STR?704,"Stuck? Well... Don't go on if you haven't been to the Abandoned Ship with the Morpher captain."
	.GSTR STR?264,"stun gun"
	.GSTR STR?248,"Stunt Ship"
	.GSTR STR?51,"Suddenly, as you "
	.GSTR STR?468,"sunglasses"
	.GSTR STR?430,"superbrief"
	.GSTR STR?94,"Superbrief"
	.GSTR STR?475,"survivable"
	.GSTR STR?145,"swiping"
	.GSTR STR?113,"take"
	.GSTR STR?891,"TAKE ALL BUT THE BLUE FROB."
	.GSTR STR?890,"TAKE EVERYTHING."
	.GSTR STR?889,"TAKE MY GOWN."
	.GSTR STR?902,"TAKE THE DINNER, THE TOWEL AND THE FRUIT. TIE THE TOWEL AROUND MY HEAD. DROP THE FRUIT."
	.GSTR STR?903,"TAKE THE PLANT THEN EAT IT."
	.GSTR STR?114,"taking"
	.GSTR STR?842,"TEA"
	.GSTR STR?476,"technology"
	.GSTR STR?448,"television"
	.GSTR STR?77,"TELL ME ABOUT"
	.GSTR STR?100,"TESTERS"
	.GSTR STR?537,"That said, you started at the end last game."
	.GSTR STR?544,"That should be enough."
	.GSTR STR?655,"That should be good."
	.GSTR STR?17,"That's precisely the sort of stuff that you'll have to do yourself."
	.GSTR STR?351,"The area is busy with people, who talk to each other, taking glances at you occasionally in surprise. Heading north will lead you to the First Class. In front of the door, however, is a buff bouncer blocking the entrance. To the east is a door labelled ""NO ENTRY"", and below it in tiny letters: ""under penalty of death"". West is a room which has tape all around it, presumably under maintenance. To the southeast is the Kitchen, while southwest is the Third Class."
	.GSTR STR?353,"The area is under maintenance."
	.GSTR STR?323,"the Beast's name"
	.GSTR STR?934,"The bills aren't important."""
	.GSTR STR?689,"The Blaster isn't working. He won't accept it."
	.GSTR STR?553,"The blue frob is important, probably."
	.GSTR STR?336,"The crater lip continues northeast and southeast here, and below you is a ledge."
	.GSTR STR?335,"The crater lip continues northeast and southeast here, and below you is a ledge. If you fell from here to the ledge you would probably break an ankle and nobody would hear you screaming and you would die from pain and exposure. On the other hand, if you climbed down carefully, you'd have no trouble. So what are you making all the fuss about?"
	.GSTR STR?334,"The crater lip leads north-east and north-west. Below you is a build-your-own-dead-whale kit (glue not included). There's no way down."
	.GSTR STR?45,"The cupboard seems unimpressed, guiding your hand away so you grasp empty air. ""You can't replace it, can you?"""
	.GSTR STR?391,"The door isn't open."
	.GSTR STR?358,"The first class is spacious, with a stage at the northern end (for Max Quordlepleen's performance), and an exit at the southern end of the room."
	.GSTR STR?940,"the glacier splits in half and sends you plunging into ice-cold water without any protection whatsoever"
	.GSTR STR?397,"The head chef is glaring at you."
	.GSTR STR?24,"The Hitchhiker's Guide to the Galaxy"
	.GSTR STR?371,"The junction leads off randomly in different directions. If you want to exit, you can go in one of in the four cardinal directions."
	.GSTR STR?370,"The junction you stand in is mostly empty. Corridors lead north, south, east and west to different parts of the ship."
	.GSTR STR?332,"The land is barren and cold - to the north is the ramp back to the Heart of Gold; to the south-east, there's an unhealthy-looking crater."
	.GSTR STR?337,"The ledge lies halfway between the crater lip and the floor of the whale crater itself. It doesn't seem quite like any ledge you've encountered before, perhaps because of the pillars on either side of you and the rather nice wall - marble, perhaps, or ivory? - hidden from sight behind you and the steep but survivable slope down to the crater floor."
	.GSTR STR?239,"the loose bolt"
	.GSTR STR?629,"The mice at this point are very confused, which may be good, depending on how you look at it."
	.GSTR STR?214,"The mice take you walking over as an opportunity to shoot you, which they do."
	.GSTR STR?399,"The morpher captain is on the floor, stunned."
	.GSTR STR?305,"The panel has already been removed. Doing that"
	.GSTR STR?271,"The pillar drops at an alrming rate (to you, at least, who is on the pillar) and plunges into the water. Well, you didn't move, as I suggested before, and you take enough damage from the shock of the ice water and die."
	.GSTR STR?376,"The pillar has collapsed."
	.GSTR STR?42,"the Question of the Answer to the Question of Life, the Universe and Everything"
	.GSTR STR?703,"The Reception is empty, there's no way to register here."
	.GSTR STR?333,"The rim of the whale crater leads northwest and southwest. The scene of the whale's final disillusionment lies below you, but there's no way down."
	.GSTR STR?274,"the rocks at a speed which can (and does) break all of your bones."
	.GSTR STR?849,"The section tells where each footnote is referenced in the game. Once again, you shouldn't develop this section until you've finished."
	.GSTR STR?1020,"the sleeping quarters"
	.GSTR STR?380,"The slope leads down to the north (where you can see some unwelcoming rocks and no sight or pretty view to behold), or up in the other direction to a cozy-looking chamber, which looks much nicer than your current area."
	.GSTR STR?331,"The surface of Magrathea is barren and inhospitable: a cold, constant wind, a sifting of dust, no sign of life or movement. Except for a strong fishy odour.

The ramp lies upwards to the north; to the south-east, there's an unhealthy-looking crater."
	.GSTR STR?843,"THE THEORY OF THEORIES"
	.GSTR STR?384,"The trail leads north; and continues southeast, turning northeast after some time."
	.GSTR STR?26,"the water (mildly salty, you must admit) which has more of an impact to your body than multiple matter transference beams."
	.GSTR STR?925,"The wind howls, chilling you to the bone."
	.GSTR STR?924,"The wind whips at your face, making you shiver as it freezes your skull."
	.GSTR STR?487,"The word"
	.GSTR STR?479,"themselves"
	.GSTR STR?745,"Then drop the open tin in an open area like the Junction, hide in another room, and wait."
	.GSTR STR?679,"Then go to GETTING THE ACCESS CARD if you really don't understand."
	.GSTR STR?607,"Then try using that sense."
	.GSTR STR?700,"Then you are told to sign your name on the phone."
	.GSTR STR?640,"Then, on the final free turn, OUT."
	.GSTR STR?594,"Then, you need to EXAMINE THE PLANT."
	.GSTR STR?345,"There are a lot of loud noises all around you, coming from bullets, alarms, and the big hot computer behind you. Not your idea of a perfect holiday, then again, who said this was a holiday?"
	.GSTR STR?395,"There is a big pink bath in the middle of the room, containing the captain of the ship."
	.GSTR STR?355,"There is a bottle of mineral water here."
	.GSTR STR?374,"There is a brick here which looks in a bad state."
	.GSTR STR?406,"There is a copy of The Hitchhiker's Guide here."
	.GSTR STR?369,"There is a DVD lying around."
	.GSTR STR?366,"There is a green frob of randomness here."
	.GSTR STR?361,"There is a notebook here."
	.GSTR STR?381,"There is a path which leads back to the Cavern, down the slope. To the east is the other side of the chasm, but there's a large gap. Not as large as you thought it would be, but large enough that you can't jump across it."
	.GSTR STR?718,"There is a sink in the Kitchen of Milliways."
	.GSTR STR?566,"There is a small ridge around the middle."
	.GSTR STR?365,"There is a weirdbox here."
	.GSTR STR?364,"There is an egg here. A platinum one."
	.GSTR STR?632,"There is one turn between each of the questions, where the mice are talking."
	.GSTR STR?694,"There you go."
	.GSTR STR?347,"There's a big computer there."
	.GSTR STR?651,"There's a door that he walks through which you aren't allowed to enter."
	.GSTR STR?961,"There's another turn down the drain."
	.GSTR STR?383,"There's no way back."
	.GSTR STR?35,"There's not enough room.
"
	.GSTR STR?729,"There's nothing here."
	.GSTR STR?926,"There's so much cold you handle, and the fact that you are shivering suggests this is too much."
	.GSTR STR?154,"Thing"
	.GSTR STR?155,"thing your aunt gave you which you don't know what it is"
	.GSTR STR?576,"Think about the reason you died."
	.GSTR STR?584,"Think about this in a different way. There's this weird radio you can see."
	.GSTR STR?953,"Think again."
	.GSTR STR?232,"third class access door"
	.GSTR STR?233,"third class access panel"
	.GSTR STR?461,"third-class"
	.GSTR STR?935,"This better hold my weight..."""
	.GSTR STR?377,"This chamber is small but sparse, and you feel at home here. What you mean by home, you don't know. If you're not feeling at all comfortable here, you can either go north, or follow the northeast path or the southeast path."
	.GSTR STR?574,"This crater... how do I get down it?"
	.GSTR STR?342,"This is a dead end. The only way out is down a set of stairs."
	.GSTR STR?196,"This is something which is going to happen to you quite a lot, so you might as well get used to it."
	.GSTR STR?392,"This is the bottom of the stairs. A sofa is wedged in the staircase above you and the top of the stairs, and a door leads north onto the street."
	.GSTR STR?348,"This is the car park. All is silent, other than an old, buzzing light on the ceiling which probably needs replacing and the odd sound of a maintenance robot scrubbing the toilet. There is nothing of great importance here that you would need right away, though the toilet is to the south, and the time-teleport cubicle is to the north.

To the west, you can go back to the Reception, or to the east where ther is a large ship (apparently Hotblack Desiato's ship), which is the only one that stands out from the other ships."
	.GSTR STR?343,"This is the chamber of a great device named (appropriately) The Great Device. It looks like it should calculate something important, you just can't tell what. The only path leads east, back into the maze of hallways. However, it looks like you may be able to squeeze around the computer, to the northwest and southwest."
	.GSTR STR?338,"This ledge lies halfway between the crater lip and the floor of the whale crater itself."
	.GSTR STR?756,"This section should only be used as a last resort, or for your own interest after you've completed the game."
	.GSTR STR?541,"This space has been intentionally left blank."
	.GSTR STR?621,"This time, you must PUSH/FEEL LUMP."
	.GSTR STR?385,"This trail is a continuation of the last one, and continues southwest, turning northwest after some time; as well as a northern path."
	.GSTR STR?437,"three-dig"
	.GSTR STR?794,"throwing the fruit at the mice?"
	.GSTR STR?1012,"tingly"
	.GSTR STR?560,"To be specific, they aren't actually your friends. They only keep you on the ship because..."
	.GSTR STR?803,"to SING? Or DANCE?"
	.GSTR STR?349,"To the south is the toilet, to the west is the Reception, east leads to a hundred strange-looking ships (including Hotblack Desiato's cruiser, which is all that you can look at), and north to the time-teleport cubicles."
	.GSTR STR?944,"Tom, Looe ""Napoleon"" Leferv, Eergon Chakasa, G-g-g-g-gsipolosotanentyhdezxamarequlat O"
	.GSTR STR?136,"too far away"
	.GSTR STR?320,"toothbrush"
	.GSTR STR?844,"TOWEL"
	.GSTR STR?426,"transcript"
	.GSTR STR?87,"tri"
	.GSTR STR?1044,"tripped on a rock sticking out of the ground"
	.GSTR STR?921,"trudges after you, remarking about how much further your weak legs could carry you"
	.GSTR STR?923,"trundles slowly, complaining about how rubbish your life must be"
	.GSTR STR?929,"Trust me."""
	.GSTR STR?683,"Try asking him about the cupboards."
	.GSTR STR?554,"Try consulting the Guide about it."
	.GSTR STR?605,"Try different things, like reading what it tells you."
	.GSTR STR?565,"Try examining it."
	.GSTR STR?639,"Try GO TO THE EXIT. Then on the next free turn, PUSH THE BUTTON."
	.GSTR STR?678,"Try it now."
	.GSTR STR?734,"Try looking around a lot more."
	.GSTR STR?673,"Try pouring the Blaster into a glass."
	.GSTR STR?407,"Try: CONSULT GUIDE ABOUT (something)."
	.GSTR STR?115,"trying to enter"
	.GSTR STR?791,"trying to kill yourself with the sporfe?"
	.GSTR STR?32,"t's a bright morning, the sun is shining, the birds are singing, the meadows are blooming"
	.GSTR STR?206,"tumble"
	.GSTR STR?140,"turn off"
	.GSTR STR?141,"turn on"
	.GSTR STR?1042,"turned on the spot to try and keep warm"
	.GSTR STR?998,"Two drops fall out of the tap"
	.GSTR STR?981,"Twopenny-Halfpenny"
	.GSTR STR?802,"typing QWERTY?"
	.GSTR STR?804,"typing WHY? Or WHAT?"
	.GSTR STR?356,"Uh oh! You notice a bottle of Pan Galactic Gargle Blaster here."
	.GSTR STR?943,"Uncle Fleppe, Quarck Jenkins, Xgrrphlak, Karen Zog"
	.GSTR STR?413,"underneath"
	.GSTR STR?720,"Underneath the sink are a tangle of pipes and bolts, etc. One the of the bolts are loose."
	.GSTR STR?19,"Unexpectedly, the button sets off an electrical spark near the oxygen tanks, and the whole ship explodes, killing you and destroying everything inside with it in a huge fireball. This stunt was recorded from a concert on a nearby planet, and made 62 views across the Sub-Etha net before it was taken down as spam."
	.GSTR STR?205,"Unfortunately, you don't get to do much after that, because you trip up in the dark trying to stand, and impale yourself (in a very un-family-friendly way) on a shard of bone. This means..."
	.GSTR STR?1029,"uninhabitable"
	.GSTR STR?469,"unintelligible"
	.GSTR STR?120,"unlocked"
	.GSTR STR?442,"unpleasant"
	.GSTR STR?163,"unplugging"
	.GSTR STR?980,"Unsatisfactory"
	.GSTR STR?905,"unusual"
	.GSTR STR?446,"unwelcoming"
	.GSTR STR?62,"up"
	.GSTR STR?743,"Use the sporfe from the Interview Room to open it, because the sporfe is very sharp."
	.GSTR STR?736,"Use the stun gun from the Junction."
	.GSTR STR?568,"Use your senses, like in the Dark."
	.GSTR STR?963,"Useless. Utterly useless."
	.GSTR STR?463,"vantablack"
	.GSTR STR?1027,"vast"
	.GSTR STR?83,"verb"
	.GSTR STR?96,"Verbose"
	.GSTR STR?1015,"vibrate"
	.GSTR STR?988,"Vogons."
	.GSTR STR?189,"wait until"
	.GSTR STR?642,"WAIT."
	.GSTR STR?519,"waiting patiently"
	.GSTR STR?1039,"walk"
	.GSTR STR?516,"walking along"
	.GSTR STR?215,"walking over to"
	.GSTR STR?213,"walking over to the south wall"
	.GSTR STR?788,"Walking southeast or southwest from the ramp?"
	.GSTR STR?1011,"warm"
	.GSTR STR?362,"WARNING: Use for cybrids only."
	.GSTR STR?985,"Washout"
	.GSTR STR?514,"watching you"
	.GSTR STR?938,"We look great in these, Joe. There is no way either of us will be pushed down the stairs in work and end up in hospital with ten minutes left to live."""
	.GSTR STR?1025,"wearing barely nothing whilst you look for an easy way off"
	.GSTR STR?599,"Well done."
	.GSTR STR?933,"We'll make it out alive."""
	.GSTR STR?684,"Well, according to him, you give it something to be distracted with, and then take whatever it has in store."
	.GSTR STR?665,"Well, if you need to, you can ask the Guide about some of the objects there."
	.GSTR STR?375,"Well... There's no way to the northwest anymore."
	.GSTR STR?588,"Well... what do you think?"
	.GSTR STR?317,"were"
	.GSTR STR?70,"west"
	.GSTR STR?949,"What a concept."
	.GSTR STR?586,"What about the plant on the ledge?"
	.GSTR STR?587,"What ABOUT the plant on the ledge?"
	.GSTR STR?491,"What charming language!"
	.GSTR STR?567,"What could that mean?"
	.GSTR STR?748,"What do I do with the auto-sign pen?"
	.GSTR STR?695,"What do I do with the Policeman?"
	.GSTR STR?548,"What is the thing?"
	.GSTR STR?709,"What source could know the most about dinner (seeing as you're in Milliways, so dinner seems appropriate)?"
	.GSTR STR?707,"When I diagnose myself, I'm apparently hungry. How do I fix that?"
	.GSTR STR?746,"When the sandcrab ""begins clicking its claws"", run into the room and stab the crab with sporfe."
	.GSTR STR?871,"When you are stuck on where you can move, LOOK AROUND for some exits in the room description.
[To return to the previous menu, press Q, or to return to playing the game, press the escape key.]"
	.GSTR STR?750,"When you return to Milliways, you will notice a police agent. Look at that section, then return here."
	.GSTR STR?719,"When you try to turn it on, there is not enough water, so you will have to try and fix it."
	.GSTR STR?555,"Where did the Guide go? And what about my friends?"
	.GSTR STR?845,"WHITE MICE"
	.GSTR STR?967,"Why bother?"
	.GSTR STR?645,"Why don't you figure that out yourself?"
	.GSTR STR?846,"WIKKIT KEY"
	.GSTR STR?582,"Will he follow you?"
	.GSTR STR?456,"windscreen"
	.GSTR STR?455,"windshield"
	.GSTR STR?470,"wine-bottle"
	.GSTR STR?616,"With hearing, if there is a ""noise reverberating"" in the Dark, you are going to Dirk Gently's office; and if there is a ""sound echoing"" in the darkness around you, it will be the Planetary Design Workshop."
	.GSTR STR?618,"With smell, you will end up in the Golgafrincham Ark B when you detect the ""sweet, bubble bath"" - and at the Big Bang Burger Bar when you can smell something ""strong, like a barbecue""."
	.GSTR STR?971,"won't help any"
	.GSTR STR?1018,"worble"
	.GSTR STR?81,"word"
	.GSTR STR?979,"Worthless"
	.GSTR STR?25,"y swiftly grabs a Kill-O-Zap gun and fires a load of bullets at you. You surprisingly catch them all, a feat which you have never accomplished before, and you slide to the floor."
	.GSTR STR?730,"Yes there is."
	.GSTR STR?710,"Yes, the Hitchhiker's Guide."
	.GSTR STR?648,"Yes."
	.GSTR STR?897,"YES."
	.GSTR STR?431,"yes-object"
	.GSTR STR?286,"you"
	.GSTR STR?56,"You already are!"
	.GSTR STR?956,"You appear to have gone barking mad."
	.GSTR STR?379,"You are at the bottom of a slope. You can see a view out to the north. But in all honesty, the view isn't at all worth what the journey down the slope made it out to be. In your head, you imagined a beautiful sight, with maybe a sunset shining down on you, red and orange light making you look like the hero character from some movie you might have watched when you were little.
Well, damn your imagination, because this sight couldn't be more unwelcoming. 
Rocks, sharp and horrible, point at you, as if condemning you to join them in a life of misery and many other emotions you know Marvin would have. But now you're having those emotions too. Above you, a dark grey sky looms over the fjords you stand in, warning the two inhabitants of the land of the destruction and obliteration to come (in about two million years, you suppose). On the bright side, this means you should have enough time to find the philosophical word that you were tasked with finding and get out of here.

To the south, you can see a large but comfortable-looking chamber, up the slope. Right now, you'd rather be there than here."
	.GSTR STR?390,"You are at the top of the stairs. Below you, a daunting sofa is wedged painfully in the staircase."
	.GSTR STR?955,"You are clearly insane."
	.GSTR STR?501,"You are disoriented. Blackness swims toward you like a shoal of eels who have just seen something that eels like a lot..."
	.GSTR STR?38,"You are obviously letting things get to you. You should learn to relax a little.
"
	.GSTR STR?382,"You are on the east side of the crevasse. You can only go south."
	.GSTR STR?211,"You begin to feel a little sick. From that point, it escalates quickly until it reaches the point where you realise the fruit was obviously poisoned, and...

Well. I don't want to be the one who has to tell you, do I?"
	.GSTR STR?210,"You begin to feel a little sick...

""The stuff in that fruit worked quickly, didn't it?"" says one disembodied voice. 
""Of course,"" says another. ""You know where I buy everything from."" 
""Yeah, yeah. Anyway, let's begin.""

On, the upside, you felt no pain."
	.GSTR STR?352,"You can go southwest (to the Third Class area), southeast (to the kitchen), east (although there is a door stating ""NO ENTRY"") and north leads to the first class."
	.GSTR STR?59,"You can hear "
	.GSTR STR?1065,"You can live without needing to enter there."
	.GSTR STR?60,"You can see "
	.GSTR STR?357,"You can see a bottle with some Pan Galactic Gargle Blaster here."
	.GSTR STR?372,"You can see a chair here."
	.GSTR STR?388,"You can see a chatterbox here - AKA the fortune teller."
	.GSTR STR?868,"You can type commands such as GO NORTH( which can be simplified to N), SOUTH( simplified to S), E( for EAST), and W( for WEST), Followed by the ENTER button. [Press ENTER to get another hint.]"
	.GSTR STR?33,"You can't "
	.GSTR STR?951,"You can't be serious."
	.GSTR STR?341,"You can't go back in there! That's extremely dangerous!"
	.GSTR STR?346,"You can't go back! You'd die!"
	.GSTR STR?1061,"You can't see any beast here, which is pretty lucky."
	.GSTR STR?1063,"You can't see the Ravenous Bugblatter Beast of Traal here. You don't think you can, anyway."
	.GSTR STR?577,"You died because you didn't have enough light. You tripped up and died."
	.GSTR STR?36,"You don't find anything new there.
"
	.GSTR STR?1066,"You don't have to go there."
	.GSTR STR?545,"You don't know what that is? Pathetic!"
	.GSTR STR?34,"You don't need to refer to that.
"
	.GSTR STR?485,"You don't need to use the word"
	.GSTR STR?203,"You fall into the new-ish, nasty-ish crater, where the blubber and blood liberally spattered around break your fall. Unfortunately, however, on becoming aware of your surroundings, you die of disgust."
	.GSTR STR?14,"You feel the stunning blow of an aptly-named Stun Gun (trademark of Sirius Cybernetics Co) as he shoots you at point-blank range. Thinking quickly about what to do before his friends teleport over for a party, the captain sends you on your way via the airlock. Unfotunately, no ship comes to pick you up this time."
	.GSTR STR?954,"You have lost your mind."
	.GSTR STR?50,"You have to specify a number between 0 and 9.
"
	.GSTR STR?15,"You hear a large cheer as the whole world is shut off."
	.GSTR STR?1002,"You hear?"
	.GSTR STR?711,"You know exactly what to get now."
	.GSTR STR?207,"You leap messily to your death. It's quick, painless and fishy."
	.GSTR STR?973,"You may know how to do that, but I don't."
	.GSTR STR?481,"You may know what"
	.GSTR STR?197,"You might not think it's very fair, but nobody said the Galaxy was a very fair place anyway."
	.GSTR STR?733,"You must be a bit more cautious."
	.GSTR STR?974,"You must tell me how to do that."
	.GSTR STR?676,"You must use the wine glass."
	.GSTR STR?619,"You need to ENTER THE DARK ROOM when you arrive hear. (Get it?)"
	.GSTR STR?493,"You ought to be ashamed of yourself!"
	.GSTR STR?927,"You shiver, the icy air hanging around you like a deadline, slowly deteriorating your mind and body."
	.GSTR STR?1062,"You should be glad you can't see any Beast here."
	.GSTR STR?725,"You should know from the Hitchhiker's Guide that you need specifically a spoonful."
	.GSTR STR?727,"You should pour the Blaster with the sporfe (yes, I'm sorry, but I'm not clever enough to be able to use three nouns), which is satisfying enough for me."
	.GSTR STR?666,"You should read up on Pan Galactic Gargle Blasters if you haven't already."
	.GSTR STR?783,"You shouldn't develop anything in this section until you've finished the game. Things in the section will invariably give away the answers to puzzles in the game."
	.GSTR STR?602,"You will need to wait."
	.GSTR STR?573,"You won't need this yet. But it will be helpful later on."
	.GSTR STR?617,"You'll have to DROP THE THING that you have noticed in your hand."
	.GSTR STR?740,"You'll need to distract it long enough to kill it."
	.GSTR STR?405,"Your gown appears to have slipped through the hatchway, and is now on the floor."
	.GSTR STR?277,"you're"
	.GSTR STR?285,"yourself"
	.GSTR STR?575,"You've died in it, have you?"
	.GSTR STR?261,"zap"
	.GSTR STR?847,"ZAPHOD BEEBLEBROX"
	.GSTR STR?948,"Zaphod Beeblebrox, Tootha, Aaron Eat'em, Yu Katchas"
	.ENDI
